import { FlatCompat } from "@eslint/eslintrc";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "agent-output/**",
      "docs/**",
      "*.config.*",
      // Auto-generated by `next build` (Next 15.5 adds a typed-routes triple-slash
      // reference that the ts triple-slash-reference rule flags). Never hand-edited.
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
